name: Cypress Tests
on: [push, pull_request]

env:
  NODE_VERSION: 20

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    environment: CI
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
      
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          start: pnpm dev
          wait-on: 'http://localhost:3000'
          command: pnpm test:e2e
          record: ${{ github.event_name == 'push' && secrets.CYPRESS_RECORD_KEY != '' }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }} 